"""Add section_order to Sections

Revision ID: 464dc05a1acd
Revises: dd9bafb44d2e
Create Date: 2025-06-22 21:38:26.718499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464dc05a1acd'
down_revision = 'dd9bafb44d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_order', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_section', sa.Integer(), nullable=True))
        batch_op.drop_column('assign_role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assign_role', sa.INTEGER(), nullable=True))
        batch_op.drop_column('main_section')

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_column('section_order')

    # ### end Alembic commands ###
