"""changing main section

Revision ID: d7a59d5feb36
Revises: 464dc05a1acd
Create Date: 2025-06-22 23:16:06.997370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a59d5feb36'
down_revision = '464dc05a1acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('main_section')

    with op.batch_alter_table('users_sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_section', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_sections', schema=None) as batch_op:
        batch_op.drop_column('main_section')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_section', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
