task_list  = [{'section':'Dismantler', 'tasks': [
                                                {'task_name':'Quantity check','task_description':'The chairs match the assigned chairs quantity'},
                                                {'task_name':'Article number check','task_description':'The chairs  backrests, and wood frame have the correct article numbers.'},
                                                {'task_name':'Chairs are Dismantle','task_description':'The seats and backrests have been disassembled.'},
                                                {'task_name':'Parts placement','task_description':'Screws and extra parts are labeled and placed in their designated position in the trolley.'},
                                                {'task_name':'Items placement','task_description':'The chair frame, seats, and backrests are placed in their designated position in the trolley.'},
                                                ]},
            {'section':'Cleaner', 'tasks': [
                                            {'task_name':'Quantity check',
                                             'task_description':'The chairs frames match the assigned chairs quantity '},
                                            {'task_name':'Article number check',
                                             'task_description':'The chairs wood frame have the correct article numbers.'},
                                            {'task_name':'Frames are washed',
                                             'task_description':'The chairs frame are washed '},
                                            {'task_name':'Frames are oiled',
                                             'task_description':'The chairs frame are oiled'},
                                            {'task_name':'Frames are label',
                                             'task_description':'The chair’s frames are labeled with the designated article number label'},
                                            {'task_name':'frames placement',
                                             'task_description':'The chairs frames are placed in the designated position in the trolley'},
                                            ]},
            {'section':'Upholstery Remover', 'tasks': [
                                            {'task_name':'Quantity check',
                                             'task_description':'The seat and backrest match the specified chair quantity'},
                                            {'task_name':'Article number check',
                                             'task_description':'The seats and backrests have the correct article numbers'},
                                            {'task_name':'upholstery is removed',
                                             'task_description':'The seats and backrests old upholstery have been removed '},
                                            {'task_name':'Items placement',
                                             'task_description':'The seats and backrests are placed in their assigned positions in the trolley'},
                                            ]},
            {'section':'Foam Installer', 'tasks': [
                                            {'task_name':'Quantity check',
                                             'task_description':'The seat and backrest match the specified chair quantity'},
                                            {'task_name':'Article number check',
                                             'task_description':'The seats and backrests have the correct article numbers'},
                                            {'task_name':'Foams are installed',
                                             'task_description':'The foam is installed in the seats and backrest'},
                                            {'task_name':'Foams are trimmed',
                                             'task_description':'The foam is trimmed on the seats and backrest'},
                                            {'task_name':'Items placement',
                                             'task_description':'The seats and backrests are placed in their assigned positions in the trolley'},
                                            ]},
            {'section':'Upholstery Installer', 'tasks': [
                                            {'task_name':'Quantity check',
                                             'task_description':'The seat and backrest match the specified chair quantity'},
                                            {'task_name':'Article number check',
                                             'task_description':'The seats and backrests have the correct article numbers'},
                                            {'task_name':'Upholsteries are installed',
                                             'task_description':'The upholstery is installed on the seats and backrests'},
                                            {'task_name':'Parts are label',
                                             'task_description':'The article numbers have been placed back to the seats and backrests'},
                                            {'task_name':'Items placement',
                                             'task_description':'The seats and backrests are placed in their assigned positions in the trolley'},
                                            ]},
             {'section':'Wood Frame Fixer', 'tasks': [
                                            {'task_name':'Quantity check',
                                             'task_description':'The wood frames match the specified chair quantity'},
                                            {'task_name':'Article number check',
                                             'task_description':'The wood frames have the correct article numbers.'},
                                            {'task_name':'Frame is stable',
                                             'task_description':'The wood frame has been reglue or was stable from the beginning'},
                                            {'task_name':'Glue residue',
                                             'task_description':'There is no glue residue on the chair frames'},
                                            {'task_name':'Frame restoration',
                                             'task_description':'The wood frames scratches, holes  and  stains have been restored'},
                                             {'task_name':'Parts placement',
                                             'task_description':'the wood frames have been placed in its assign position in the trolley'},
                                            ]},
            {'section':'Remontering', 'tasks': [
                                            {'task_name':'Quantity check seats',
                                             'task_description':'The seats and backrests match the specified quantity for the chair'},
                                             {'task_name':'Quantity check chairs',
                                             'task_description':'The wood frames match the specified chair quantity'},
                                            {'task_name':'Article number check wood frames',
                                             'task_description':'The wood frames have the correct article number labels'},
                                             {'task_name':'Article number check seats',
                                             'task_description':'The seats and backrest have the correct article number label'},

                                            {'task_name':'Chairs are mantled',
                                             'task_description':'The chairs seats and backrest are mantled'},
                                            {'task_name':'Parts are stable',
                                             'task_description':'The seats and backrests are stable.'},
                                            {'task_name':'Legs have pads',
                                             'task_description':'The chair has leg pads installed'},
                                            {'task_name':'Upholstery is clean',
                                            'task_description':'The upholstery is clean'},
                                            {'task_name':'Frames are oiled',
                                            'task_description':'the wood frames have been placed in its assign position in the trolley'},
                                            {'task_name':'Items placement',
                                            'task_description':'The chairs have been placed in their designated positions in the trolley'},
                                            ]}, 
            {'section':'Photography', 'tasks': [
                                            {'task_name':'Quantity check',
                                             'task_description':'The items match the corresponding quantity specify'},
                                            {'task_name':'Article number check',
                                             'task_description':'The Items have the correct article number'},
                                             {'task_name':'Defects check',
                                             'task_description':'Are there any defects with the items that can be fixed'},
                                            {'task_name':'Items are photograph',
                                             'task_description':'The Items have been photograph'},
                                            {'task_name':'Items placement',
                                             'task_description':'The Items have been placed in their assigned positions'},
                                            {'task_name':'Webshop publication',
                                             'task_description':'The items are ready for publication on the webshop'},
                                            
                                            ]},

                   
            ]